repos:
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.22
    hooks:
      - id: terraform-fmt
      - id: tflint
      - id: shellcheck
      - id: markdown-link-check
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.5.2
    hooks:
      - id: commitizen
